package Entity;
// Generated 2020-06-25 23:23:55 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name="notification"
    ,catalog="users"
)
public class Notification  implements java.io.Serializable {


     private Integer notificationId;
     private String clientId;
     private String priorityId;
     private String categoryId;
     private String servicemanId;
     private String subject;
     private String description;

    public Notification() {
    }

    public Notification(String clientId, String priorityId, String categoryId, String servicemanId, String subject, String description) {
       this.clientId = clientId;
       this.priorityId = priorityId;
       this.categoryId = categoryId;
       this.servicemanId = servicemanId;
       this.subject = subject;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="NotificationID", unique=true, nullable=false)
    public Integer getNotificationId() {
        return this.notificationId;
    }
    
    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }

    
    @Column(name="ClientID", nullable=false)
    public String getClientId() {
        return this.clientId;
    }
    
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    
    @Column(name="PriorityID", nullable=false)
    public String getPriorityId() {
        return this.priorityId;
    }
    
    public void setPriorityId(String priorityId) {
        this.priorityId = priorityId;
    }

    
    @Column(name="CategoryID", nullable=false)
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="ServicemanID", nullable=false)
    public String getServicemanId() {
        return this.servicemanId;
    }
    
    public void setServicemanId(String servicemanId) {
        this.servicemanId = servicemanId;
    }

    
    @Column(name="Subject", nullable=false)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="Description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


